version: '3'
services:

  # The Database
  database:
    image: postgres:11-alpine
    environment:
      - POSTGRES_DB=blog_app
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=secret
    volumes:
      - db-data:/var/lib/postgresql/data

  service-api:
    build:
      context: .
      dockerfile: ./bin/service-api.dockerfile
    ports:
     - 8100:8000
    volumes:
     - ./app:/opt/application
    environment:
      APP_GUNICORN_USE: app.wsgi:application
      APP_MIGRATE: 1
    env_file:
      - .env

volumes:
  db-data: {}
